# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\Vwo1000\wd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(60, 460, 75, 23))
        self.startButton.setObjectName("startButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(600, 470, 75, 23))
        self.exitButton.setObjectName("exitButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(420, 450, 75, 23))
        self.saveButton.setObjectName("saveButton")
        self.pauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.pauseButton.setGeometry(QtCore.QRect(220, 470, 75, 23))
        self.pauseButton.setObjectName("pauseButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 500, 281, 91))
        self.textBrowser.setObjectName("textBrowser")
        self.nativeVideo = QtWidgets.QLabel(self.centralwidget)
        self.nativeVideo.setGeometry(QtCore.QRect(30, 50, 384, 216))
        self.nativeVideo.setObjectName("nativeVideo")
        self.postproVideo = QtWidgets.QLabel(self.centralwidget)
        self.postproVideo.setGeometry(QtCore.QRect(490, 40, 384, 216))
        self.postproVideo.setObjectName("postproVideo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.startButton.clicked['bool'].connect(MainWindow.clickStart) # type: ignore
        self.pauseButton.clicked.connect(MainWindow.clickPause) # type: ignore
        self.saveButton.clicked.connect(MainWindow.clickSave) # type: ignore
        self.exitButton.clicked['bool'].connect(MainWindow.clickExit) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.startButton, self.pauseButton)
        MainWindow.setTabOrder(self.pauseButton, self.saveButton)
        MainWindow.setTabOrder(self.saveButton, self.exitButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.nativeVideo.setText(_translate("MainWindow", "TextLabel"))
        self.postproVideo.setText(_translate("MainWindow", "TextLabel"))
